//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsApi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableNewsUpdate
    {
        public int NewsId { get; set; }
        public string Title { get; set; }
        public string Exerpt { get; set; }
        public string Source { get; set; }
        public string Category { get; set; }
        public string Region { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual TableUser TableUser { get; set; }
    }
}
